export const colors = {
  background: '#F5F7FB',
  surface: '#FFFFFF',
  surfaceMuted: '#F8FAFC',
  surfaceRaised: '#FFFFFF',
  border: '#E2E8F0',
  borderStrong: '#CBD5E1',
  text: '#0F172A',
  textMuted: '#475569',
  textSubtle: '#64748B',
  primary: '#1D4ED8',
  primaryHover: '#1E40AF',
  primarySoft: '#DBEAFE',
  success: '#059669',
  successSoft: '#D1FAE5',
  warning: '#D97706',
  warningSoft: '#FEF3C7',
  danger: '#DC2626',
  dangerSoft: '#FEE2E2',
  info: '#2563EB',
  infoSoft: '#DBEAFE',
  memory: '#7C3AED',
  memorySoft: '#EDE9FE',
  knowledge: '#CA8A04',
  knowledgeSoft: '#FEF9C3',
  evaluation: '#0F766E',
  evaluationSoft: '#CCFBF1',
  code: '#0F172A',
} as const;

export type ColorToken = keyof typeof colors;
